package com.learn.ExceptionHandling;

import java.util.Scanner;

public class Calculator {
	public static void main(String[] args) {
		try {
			System.out.println("Calculation is started");
		Scanner scan = new Scanner(System.in);
		System.out.println("Enter a numerator");
		int num = scan.nextInt();
		System.out.println("Enter a denomenator");
		int den = scan.nextInt();
		int c = num/den;
		System.out.println("Division result is "+c);
		
		} catch (Exception e) {
			
			System.out.println("Eception is handled");
		}
			System.out.println("Calculation is ended");
	}
}
